title: Texture Theme
author: GitHub User
email: po1siontive@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is my portfolio site where you can find all the links to my accounts GitHub, LinkedIn, gmail and others. Perhaps there may occur some any content or your ad =).
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /my_simple_site
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Aleksey Drobushevsky
  tagline: Sophomore at Gomel State University. DevOps Intern at FE "IBA-Gomel"
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: po1siontive
    github:  Po1SioNTiVe
    linkedIn: in/aleksey-drobyshevsky-8b1000192/
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages: 
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
